# Generated by Django 5.2.4 on 2025-07-30 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('center', models.CharField(blank=True, max_length=1000, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('center', models.CharField(blank=True, max_length=1000, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='WaterwaySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('total_water_requirement', models.FloatField(default=0)),
                ('shape', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#0000FF', max_length=7)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='api.region')),
            ],
        ),
        migrations.CreateModel(
            name='CropPivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_name', models.CharField(max_length=10)),
                ('area', models.FloatField()),
                ('crop_1', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('crop_2', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('crop_3', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('crop_4', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('seeding_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('center', models.CharField(blank=True, max_length=1000, null=True)),
                ('radius_m', models.FloatField(default=100.0)),
                ('color', models.CharField(default='#008000', max_length=7)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pivots', to='api.waterwaysector')),
            ],
        ),
        migrations.CreateModel(
            name='CropField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_name', models.CharField(max_length=10)),
                ('area', models.FloatField()),
                ('crop_1', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('crop_2', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('crop_3', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('crop_4', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('seeding_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('center', models.CharField(blank=True, max_length=1000, null=True)),
                ('shape', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#000080', max_length=7)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.waterwaysector')),
            ],
        ),
        migrations.CreateModel(
            name='CropRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pivot_name', models.CharField(max_length=50)),
                ('sector_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('crop', models.CharField(choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50)),
                ('seeding_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('yield_tons', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pivot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations', to='api.croppivot')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('pivot', 'year', 'crop')},
            },
        ),
    ]
