# Generated by Django 5.2.4 on 2025-07-25 08:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='WaterwaySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_ha', models.FloatField(blank=True, null=True)),
                ('total_water_requirement', models.FloatField()),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='api.region')),
            ],
        ),
        migrations.CreateModel(
            name='CropPivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_name', models.CharField(blank=True, max_length=10)),
                ('area', models.FloatField()),
                ('crop_1', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('crop_2', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('crop_3', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('crop_4', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('seeding_date', models.DateField()),
                ('harvest_date', models.DateField()),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('radius_m', models.FloatField(default=100.0)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pivots', to='api.waterwaysector')),
            ],
        ),
    ]
