# Generated by Django 5.2.4 on 2025-07-26 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('crop', models.CharField(choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50)),
                ('seeding_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('yield_tons', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('pivot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='api.croppivot')),
            ],
            options={
                'unique_together': {('pivot', 'year', 'crop')},
            },
        ),
    ]
