# Generated by Django 5.2.4 on 2025-08-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_color_region_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropfield',
            name='center',
        ),
    ]
