# Generated by Django 5.2.4 on 2025-07-29 07:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_name', models.CharField(max_length=10)),
                ('area', models.FloatField()),
                ('crop_1', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('crop_2', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('crop_3', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('crop_4', models.CharField(blank=True, choices=[('none', 'None'), ('corn', 'Corn'), ('wheat', 'Wheat'), ('soybean', 'Soybean'), ('barley', 'Barley'), ('canola', 'Canola'), ('sunflower', 'Sunflower'), ('potato', 'Potato')], max_length=50, null=True)),
                ('seeding_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('color', models.CharField(default='#000080', max_length=7)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.waterwaysector')),
            ],
        ),
    ]
