# Generated by Django 5.2.4 on 2025-08-04 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_cropfield_center'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='croprotation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='croprotation',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_rotations', to='api.cropfield'),
        ),
        migrations.AddField(
            model_name='croprotation',
            name='field_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='croprotation',
            name='pivot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pivot_rotations', to='api.croppivot'),
        ),
        migrations.AlterField(
            model_name='croprotation',
            name='pivot_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='croprotation',
            unique_together={('pivot', 'field', 'year', 'crop')},
        ),
    ]
