# Generated by Django 5.2.4 on 2025-08-07 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_croprotation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('subtype', models.CharField(blank=True, max_length=100, null=True)),
                ('best_season', models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cropfield',
            name='crop_1',
        ),
        migrations.RemoveField(
            model_name='cropfield',
            name='crop_2',
        ),
        migrations.RemoveField(
            model_name='cropfield',
            name='crop_3',
        ),
        migrations.RemoveField(
            model_name='cropfield',
            name='crop_4',
        ),
        migrations.RemoveField(
            model_name='croppivot',
            name='crop_1',
        ),
        migrations.RemoveField(
            model_name='croppivot',
            name='crop_2',
        ),
        migrations.RemoveField(
            model_name='croppivot',
            name='crop_3',
        ),
        migrations.RemoveField(
            model_name='croppivot',
            name='crop_4',
        ),
        migrations.AlterUniqueTogether(
            name='croprotation',
            unique_together={('pivot', 'field', 'year')},
        ),
        migrations.AddField(
            model_name='croprotation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_rotations', to='api.company'),
        ),
        migrations.AddField(
            model_name='croprotation',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_rotations', to='api.region'),
        ),
        migrations.AddField(
            model_name='croprotation',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_rotations', to='api.waterwaysector'),
        ),
        migrations.AddField(
            model_name='cropfield',
            name='crops',
            field=models.ManyToManyField(blank=True, to='api.crop'),
        ),
        migrations.AddField(
            model_name='croppivot',
            name='crops',
            field=models.ManyToManyField(blank=True, to='api.crop'),
        ),
        migrations.RemoveField(
            model_name='croprotation',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='croprotation',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='croprotation',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='croprotation',
            name='harvest_date',
        ),
        migrations.RemoveField(
            model_name='croprotation',
            name='pivot_name',
        ),
        migrations.RemoveField(
            model_name='croprotation',
            name='sector_name',
        ),
        migrations.RemoveField(
            model_name='croprotation',
            name='seeding_date',
        ),
        migrations.RemoveField(
            model_name='croprotation',
            name='yield_tons',
        ),
        migrations.CreateModel(
            name='CropRotationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeding_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('actual_yield_tons', models.FloatField(blank=True, null=True)),
                ('expected_yield_tons', models.FloatField(blank=True, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crop')),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.croprotation')),
            ],
            options={
                'unique_together': {('rotation', 'crop')},
            },
        ),
    ]
