# Generated by Django 5.2.4 on 2025-08-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_crop_remove_cropfield_crop_1_remove_cropfield_crop_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='subtype',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='crop',
            unique_together={('name', 'subtype')},
        ),
    ]
