# Generated by Django 5.2.4 on 2025-08-08 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_crop_name_alter_crop_subtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croprotation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_rotations', to='api.company'),
        ),
        migrations.AlterField(
            model_name='croprotation',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_rotations', to='api.region'),
        ),
        migrations.AlterField(
            model_name='croprotation',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_rotations', to='api.waterwaysector'),
        ),
    ]
